package io.bluetape4k.exposed.ignite3.dialect

import java.sql.Connection
import java.sql.PreparedStatement

/**
 * Apache Ignite 3 JDBC 호환 Connection 래퍼.
 *
 * Ignite JDBC는 `prepareStatement(sql, autoGeneratedKeys)` 계열 오버로드에서
 * generated keys 미지원 예외를 던질 수 있으므로, Exposed가 DDL/기본 DML을 실행할 때는
 * 단순 `prepareStatement(sql)` 경로로 우회한다.
 */
@Suppress("JavaDefaultMethodsNotOverriddenByDelegation")
internal class IgniteConnectionWrapper(
    private val connection: Connection,
) : Connection by connection {

    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement =
        connection.prepareStatement(sql)

    override fun prepareStatement(sql: String, columnIndexes: IntArray): PreparedStatement =
        connection.prepareStatement(sql)

    override fun prepareStatement(sql: String, columnNames: Array<out String>): PreparedStatement =
        connection.prepareStatement(sql)
}
